var autoLimit = 45;
var laufenLimit = 842;
var baumLimit = 2;
var hundLimit = 2;
var trettrollerLimit = 7;
var quadratLimit;
var fotoLimit;
var kugelLimit;
var strauchLimit;
var verbotLimit;
var pennyLimit;
var mobelLimit;
var blumenLimit;
var fleckLimit;
var einsLimit = 1;
var zweiLimit = 2;
var dreiLimit = 3;
var vierLimit = 4;
var funfLimit = 5;
var sechsLimit = 6;
var siebenLimit = 7;
var achtLimit = 8;
var neunLimit = 9;
var schachspielLimit;
var graffitiLimit;
var staudeLimit;
